Fix using
Fix this:
```
julia> using HDF5
ERROR: could not open file /home/dzea/Meta.jl
 in include_from_node1 at loading.jl:88
 in reload_path at loading.jl:111
 in require at loading.jl:46
 in include_from_node1 at loading.jl:88
 in reload_path at loading.jl:111
 in require at loading.jl:46
 in include_from_node1 at loading.jl:88 (repeats 2 times)
 in reload_path at loading.jl:111
 in require at loading.jl:46
at /home/dzea/.julia/StrPack/src/StrPack.jl:10
at /home/dzea/.julia/HDF5/src/plain.jl:10
at /home/dzea/.julia/HDF5/src/HDF5.jl:1
```